config/routes.rb
Rails.application.routes.draw do
  resources :slack_members, only: %i(index edit update destroy)
  resources :books, only: %i(index edit update) do
    member do
      post :rental
      post :want_to_read
      post :return
    end
  end
  resources :orders do
    member do
      post :purchase
    end
    collection do
      get :extract_openbd_product_info
    end
  end
  root to: 'top#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

require 'cgi'
require 'json'
require 'net/http'

# for order
class Order < ApplicationRecord
  include Utility::Slack
  belongs_to :user
  has_one :book
  enum state: { order_purchase_waiting: 0, order_purchased: 10 }

  attr_reader :parsed_title, :parsed_image_path, :parsed_html

  after_create :notify_slack_ordered

  validates :title, presence: true
  validates :title, uniqueness: true, on: :check_title_unique

  scope :wait_for_purchase_a_long_time, ->(reference_date: 7.days.ago.beginning_of_day) {
    order_purchase_waiting.where('order_time < ?', reference_date)
  }

  def self.urge_to_purchased
    wait_for_purchase_a_long_time.each(&:notify_slack_urge_to_purchased)
  end

  def purchase
    create_book(
      title: title
    )
    order_purchased!
  end

  def extract_amazon_product_info!(isbn = nil)
    isbn = sanitized_isbn(isbn)
    raise OpenbdError, 'ISBNを入力してください。' if isbn.blank?

    response = fetch_openbd(isbn)
    raise OpenbdError, 'openBDから情報を取得できませんでした。' if response.blank?

    summary = response['summary'] || {}

    @parsed_title = summary['title']
    @parsed_image_path = summary['cover']
    @parsed_html = nil
    self.origin_html = @parsed_html
    self.image_path = @parsed_image_path

    response
  end

  def notify_slack_urge_to_purchased
    message = <<~"MESSAGE"
      To: #{user&.slack_name} 「#{title}」の購入は完了していますか？完了している場合は、購入済みにしてください。
      #{Rails.application.config.application_domain}/#{Rails.application.routes.url_helpers.orders_path(q: { state_eq: 0 })}
    MESSAGE
    notify_slack message
  end

  def title_duplicated?
    return false if valid?(:check_title_unique)
    return false unless errors.include?(:title)

    errors.details[:title].map { |v| v[:error] }.include?(:taken)
  end

  def allow_edit?(user)
    return false if user.blank?
    return false unless order_purchase_waiting?

    user_id == user.id
  end

  private

  def notify_slack_ordered
    message = <<~"MESSAGE"
      To: #{notify_to} #{user&.slack_name}から「#{title}」の注文依頼がありました。
      #{url}
    MESSAGE

    notify_slack message
  end

  def notify_to
    "@#{Rails.application.config.slack_notify_to}" || '@here'
  end

  def sanitized_isbn(isbn)
    isbn.to_s.delete('-').strip
  end

  def fetch_openbd(isbn)
    uri = URI.parse("https://api.openbd.jp/v1/get?isbn=#{CGI.escape(isbn)}")
    res = Net::HTTP.get_response(uri)
    raise OpenbdError, 'openBDへのリクエストに失敗しました。' unless res.is_a?(Net::HTTPSuccess)

    json = JSON.parse(res.body)
    json&.first
  rescue JSON::ParserError
    raise OpenbdError, 'openBDのレスポンス解析に失敗しました。'
  end

  class OpenbdError < StandardError; end
end

app/controllers/orders_controller.rb
# for order controller
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :purchase]

  # GET /orders
  # GET /orders.json
  def index
    @q = Order.order(id: :desc).ransack(params[:q])
    @orders = @q.result.includes(:user).page(params[:page]).per(20)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.order_time = Time.zone.now
    @order.user = current_user

    respond_to do |format|
      validation_context = params[:ignore_title_unique_validation] == false.to_s ? :check_title_unique : nil
      if @order.save(context: validation_context)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def extract_openbd_product_info
    @order = Order.new

    begin
      @order.extract_amazon_product_info!(params[:isbn])
      render :extract_openbd_product_info
    rescue Order::OpenbdError => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  def purchase
    if @order.purchase
      redirect_to books_path, notice: 'Order was successfully purchased.'
    else
      redirect_to orders_path, alert: 'Error!! Order was not purchased.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:title, :order_time, :state, :url, :origin_html, :image_path)
  end
end

app/views/orders/_form.html.haml
= form_for @order, html: {class: 'uk-form-stacked'} do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .uk-margin
    = label_tag :isbn, 'ISBN', class: 'uk-form-label'
    .uk-form-controls
      = text_field_tag :isbn, nil, class: 'uk-input js-input-isbn', placeholder: '978XXXXXXXXXX'
    .uk-form-controls
      .js-product-image
    .uk-button.uk-button-default.uk-link-reset.js-extract-openbd-product-info{ data: { 'api-url': extract_openbd_product_info_orders_path}}
      ISBNから情報を取得する
    :coffee
      $ () ->
        $('.js-extract-openbd-product-info').on 'click', ->
          api_url = $(this).data('api-url')
          isbn = $('.js-input-isbn').val()
          if isbn == ''
            alert 'please input isbn!!'
            return

          self = $(this)
          self.addClass("uk-disabled")
          $('.js-product-image').html('<div uk-spinner></div>')
          $.ajax(
            url: api_url
            type: 'get'
            data: {
              isbn: isbn
            }
          ).done((data, textStatus, jqXHR) ->
            $('.js-input-title').val(data.title)
            $('.js-input-title').addClass('uk-disabled')
            $('.js-product-image').html("<img src='" + data.image_path + "'/>")
            $('.js-input-image-path').val(data.image_path)
            return
          ).fail((jqXHR, textStatus, errorThrown) ->
            alert jqXHR.responseJSON?.error || 'Error!!'
            return
          ).always(() ->
            self.removeClass("uk-disabled")
          )
  .uk-margin
    = f.label :title, class: 'uk-form-label'
    .uk-form-controls
      = f.text_field :title, class: 'uk-input js-input-title'
  .uk-margin
    = f.label :image_path, class: 'uk-form-label'
    .uk-form-controls
      = f.text_field :image_path, class: 'uk-input js-input-image-path'
  .uk-margin
    = hidden_field_tag 'ignore_title_unique_validation', @order.title_duplicated?

    - if @order.title_duplicated?
      %b ★★★タイトルの重複エラーの場合は、このまま発注することが可能です。★★★<br/>
    = f.submit '注文する', class: 'uk-button uk-button-primary'

app/views/orders/edit.html.haml
%h1 注文情報修正

= render 'form'

= link_to '詳細', @order
\|
= link_to '戻る', orders_path

app/views/orders/index.html.haml
%h1 注文一覧

= search_form_for @q, class: 'uk-grid-small uk-background-muted uk-padding-small', html: {'uk-grid': '' } do |f|
  .uk-width-1-4
    = f.label :title_cont, 'タイトル', class: 'uk-form-label'
    .uk-form-controls.uk-inline
      = f.search_field :title_cont, class: 'uk-input'

  .uk-width-1-4
    .uk-form-controls.uk-inline{ style: 'line-height: 40px;' }
      = f.collection_check_boxes :user_id_in, [[current_user.id, '自分が注文したもので絞る']], :first, :last do |b|
        = b.label class: 'uk-form-label' do
          = b.check_box class: 'uk-checkbox'
          = b.text

  .uk-width-1-4
    = f.label :state_eq, '注文状況で絞る', class: 'uk-form-label'
    .uk-form-controls.uk-inline
      = f.select :state_eq, Order.states.map { |k, v| [I18n.t("enums.order.state.#{k}") , v]}, { include_blank: true }, class: 'uk-select'

  .uk-width-1-4.uk-text-right
    %button.uk-button.uk-button-primary
      検索

%table.uk-table.uk-table-divider.uk-table-striped.uk-table-hover.uk-table-small.uk-table-middle
  %thead
    %tr
      %th.uk-width-xlarge Title
      %th Order time
      %th.uk-text-center State
      %th.uk-text-center Order by
      %th.uk-text-center Image
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td.uk-table-link.uk-text-break
          - if order.url.present?
            = link_to order.title, order.url
          - else
            = order.title
        %td= l order.order_time, format: :short
        %td.uk-text-center= order.state_i18n
        %td.uk-text-center= order.user.name
        %td.uk-text-center
          - if order.image_path.present?
            = image_tag order.image_path, size: '55x70'
        %td
          = link_to '詳細', order
          - if order.allow_edit?(current_user)
            .uk-margin-small
            = link_to '購入済にする', purchase_order_path(order), method: :post, data: { confirm: '購入済ですか？' }
            .uk-margin-small
            = link_to '注文情報修正', edit_order_path(order)
            .uk-margin-small
            = link_to '注文取消', order, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }

= paginate @orders

app/views/orders/new.html.haml
%h1
  %i.fas.fa-cash-register
  書籍注文

= render 'form'

= link_to '戻る', orders_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @order.title
%p
  %b Order time:
  = l @order.order_time, format: :short
%p
  %b State:
  = @order.state
- if @order.url.present?
  %p
    %b Url:
    = @order.url

= link_to '戻る', orders_path