config/routes.rb
Rails.application.routes.draw do
  resources :slack_members, only: %i(index edit update destroy)
  resources :books, only: %i(index edit update) do
    member do
      post :rental
      post :want_to_read
      post :return
    end
  end
  resources :orders do
    member do
      post :purchase
    end
    collection do
      get :extract_openbd_product_info
    end
  end
  root to: 'top#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# model for books
class Book < ApplicationRecord
  include Utility::Slack
  RENTAL_LIMIT_DAYS = 30
  belongs_to :order
  belongs_to :user, optional: true
  has_one :last_rental_operation, -> { order(id: :desc) }, class_name: 'Operation::Rental'
  has_many :rental_operations, class_name: 'Operation::Rental'
  accepts_nested_attributes_for :order

  scope :rentaled, -> {
    where.not(user_id: nil)
  }

  def self.prompt_for_return
    rentaled.select(&:rented_for_a_long_time?).each(&:notify_slack_prompt_for_return)
  end

  def rented_for_a_long_time?
    return false unless rentaled?

    last_rental_operation.created_at <= RENTAL_LIMIT_DAYS.days.ago
  end

  def rentaled?
    user.present?
  end

  def rentaled_by?(user)
    user.present? && self.user == user
  end

  def notify_slack_for_want_to_rent(request_user)
    message = <<~"MESSAGE"
      To: #{user&.slack_name} 「#{title}」を、#{request_user.slack_name}が読みたいようですよ？？
    MESSAGE
    notify_slack message
  end

  def notify_slack_prompt_for_return
    message = <<~"MESSAGE"
      To: #{user&.slack_name} 「#{title}」は、まだ借りていますか？返却済みの場合は、「返す」処理をしてください。まだ借りている場合は、「延長する」処理をしてください。
      #{Rails.application.config.application_domain}/#{Rails.application.routes.url_helpers.books_path(q: { id_eq: id })}
    MESSAGE
    notify_slack message
  end

  def title_duplicated?
    return false if valid?(:check_title_unique)
    return false unless errors.include?(:title)

    errors.details[:title].map { |v| v[:error] }.include?(:taken)
  end
end

app/controllers/books_controller.rb
# controller for books
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :rental, :want_to_read, :return]

  # GET /books
  # GET /books.json
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.includes(:order).includes(:user).order(id: :desc).page(params[:page]).per(20)
  end

  # GET /books/1/edit
  def edit
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def rental
    @book.user = current_user
    respond_to do |format|
      if @book.save
        current_user.rental_operations.create(book: @book)
        format.js { render :rental}
        format.html { redirect_to books_path, notice: "#{@book.title}を借りました。" }
      else
        redirect_to books_path, alert: "「#{@book.title}」を借りるのに失敗しました。"
      end
    end
  end

  def want_to_read
    @book.notify_slack_for_want_to_rent(current_user)
    respond_to do |format|
      format.js { render :want_to_read }
    end
  end

  def return
    @book.user = nil
    if @book.save
      current_user.return_operations.create(book: @book)
      redirect_to books_path, notice: "#{@book.title}を返しました。"
    else
      redirect_to books_path, alert: "「#{@book.title}」を返すのに失敗しました。"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:location, order_attributes: [:id, :image_path])
  end
end

app/views/books/_form.html.haml
= form_for @book, html: {class: 'uk-form-stacked'} do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |message|
          %li= message

  .uk-margin
    = f.label :title, class: 'uk-form-label uk-disabled'
    = f.text_field :title, class: 'uk-input'
  .uk-margin
    = f.label :location, class: 'uk-form-label'
    = f.text_area :location, class: 'uk-input'
  .uk-margin
    = f.fields_for :order do |of|
      = of.hidden_field :id
      = of.label :image_path, class: 'uk-form-label'
      = of.text_field :image_path, class: 'uk-input'
  .uk-margin
    = f.submit '編集する'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to '戻る', books_path

app/views/books/index.html.haml
%h1 書籍一覧
= search_form_for @q, class: 'uk-grid-small uk-background-muted uk-padding-small', html: {'uk-grid': '' } do |f|
  .uk-width-1-3
    = f.label :title_cont, 'タイトル', class: 'uk-form-label'
    .uk-form-controls.uk-inline
      = f.search_field :title_cont, class: 'uk-input'

  .uk-width-1-3
    .uk-form-controls.uk-inline{ style: 'line-height: 40px;' }
      = f.collection_check_boxes :user_id_in, [[current_user.id, '自分が借りているもので絞る']], :first, :last do |b|
        = b.label class: 'uk-form-label' do
          = b.check_box class: 'uk-checkbox'
          = b.text

  .uk-width-1-3.uk-text-right
    %button.uk-button.uk-button-primary
      検索

%table.uk-table.uk-table-divider.uk-table-striped.uk-table-hover.uk-table-small.uk-table-middle
  %thead
    %tr
      %th.uk-width-xlarge  Title
      %th  Location
      %th  Purchaser
      %th.uk-text-center Image
      %th  rentaled by
      %th
      %th rental count

  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.location
        %td= "#{book.order.user.name}が発注"
        %td.uk-text-center
          - if book.order.image_path
            = image_tag book.order.image_path, size: '55x70'
        %td
          - if book.rentaled?
            = book.user.email
            %div{ id: "js-rental_datetime-#{book.id}" }
              = "レンタル日時：#{l(book.last_rental_operation.created_at, format: :short)}"
        %td
          = link_to '編集', edit_book_path(book)
          .uk-margin-small
          - if book.rentaled_by?(current_user)
            = link_to '返す', return_book_path(book), method: :post
            .uk-margin-small
            = link_to '延長する', rental_book_path(book), method: :post, remote: true
          - else
            = link_to '借りる', rental_book_path(book), method: :post, data: { confirm: '本当に借りてよろしいですか？' }
            - if book.rentaled?
              .uk-margin-small
              = link_to '読みたい！！', want_to_read_book_path(book), method: :post, data: { confirm: '読みたいリクエストを送りますか？' }, remote: true
        %td
          = book.rental_operations.count

= paginate @books

app/views/books/rental.js.erb
replace_target_element = $('#js-rental_datetime-<%= @book.id %>');
console.log(replace_target_element);
replace_target_element.html('<%= "レンタル日時：#{l(@book.last_rental_operation.created_at, format: :short)}" %>');
alert('<%= @book.title %>を延長しました');

app/views/books/want_to_read.js.erb
alert('リクエストしました');