config/routes.rb
Rails.application.routes.draw do
  resources :slack_members, only: %i(index edit update destroy)
  resources :books, only: %i(index edit update) do
    member do
      post :rental
      post :want_to_read
      post :return
    end
  end
  resources :orders do
    member do
      post :purchase
    end
    collection do
      get :extract_openbd_product_info
    end
  end
  root to: 'top#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/slack_member.rb
# frozen_string_literal: true

#  slack  member
class SlackMember < ApplicationRecord
  def self.refresh_slack_members
    return unless ENV['SLACK_ACCESS_TOKEN']

    Slack.users_list['members'].each do |u|
      SlackMember.find_or_create_by(
        slack_id: u['id'],
        slack_user_name: u['name']
      )
    end
    preset_user_id
  end

  def self.preset_user_id
    where(user_id: nil).each do |r|
      u = User.where('email like ?', "#{r.slack_user_name}@%").first
      r.update(user_id: u.id) if u.present?
    end
  end
end

app/controllers/slack_members_controller.rb
class SlackMembersController < ApplicationController
  before_action :set_slack_member, only: [:show, :edit, :update, :destroy]

  # GET /slack_members
  # GET /slack_members.json
  def index
    @slack_members = SlackMember.all
  end

  # GET /slack_members/1/edit
  def edit
  end

  # PATCH/PUT /slack_members/1
  # PATCH/PUT /slack_members/1.json
  def update
    respond_to do |format|
      if @slack_member.update(slack_member_params)
        format.html { redirect_to slack_members_path, notice: 'Slack member was successfully updated.' }
        format.json { render :show, status: :ok, location: @slack_member }
      else
        format.html { render :edit }
        format.json { render json: @slack_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slack_members/1
  # DELETE /slack_members/1.json
  def destroy
    @slack_member.destroy
    respond_to do |format|
      format.html { redirect_to slack_members_url, notice: 'Slack member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_slack_member
    @slack_member = SlackMember.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def slack_member_params
    params.require(:slack_member).permit(:slack_id, :slack_user_name, :user_id)
  end
end

app/views/slack_members/_form.html.haml
= form_for @slack_member, html: { class: "form form-horizontal slack_member" } do |f|
  .form-group
    = f.label :slack_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :slack_id, class: 'form-control', required: true
    = f.error_span(:slack_id)
  .form-group
    = f.label :slack_user_name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :slack_user_name, class: 'form-control', required: true
    = f.error_span(:slack_user_name)
  .form-group
    = f.label :user_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.select :user_id, User.pluck(:email, :id), { include_blank: true }, class: 'form-control'
    = f.error_span(:user_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), slack_members_path, :class => 'btn btn-default'

app/views/slack_members/edit.html.haml
- model_class = SlackMember
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/slack_members/index.html.haml
- model_class = SlackMember
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:slack_id)
      %th= model_class.human_attribute_name(:slack_user_name)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @slack_members.each do |slack_member|
      %tr
        %td= link_to slack_member.id, slack_member_path(slack_member)
        %td= slack_member.slack_id
        %td= slack_member.slack_user_name
        %td= slack_member.user_id
        %td=l slack_member.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_slack_member_path(slack_member), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), slack_member_path(slack_member), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'