config/routes.rb
Rails.application.routes.draw do
  resources :slack_members, only: %i(index edit update destroy)
  resources :books, only: %i(index edit update) do
    member do
      post :rental
      post :want_to_read
      post :return
    end
  end
  resources :orders do
    member do
      post :purchase
    end
    collection do
      get :extract_openbd_product_info
    end
  end
  root to: 'top#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Librarian"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_pack_tag 'application'
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    = javascript_pack_tag 'application'
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    .uk-navbar-container{ 'uk-navbar': '' }
      .uk-navbar-left
        %a.uk-navbar-item.uk-logo(href="#") Librarian
        %ul.uk-navbar-nav
          %li= link_to "書籍注文", new_order_path
          %li= link_to "注文一覧", orders_path
          %li= link_to "書籍一覧", books_path
      .uk-navbar-right
        %ul.uk-navbar-nav
          %li
            %span.uk-button.uk-button-default
              - unless user_signed_in?
                = link_to "Login", user_google_oauth2_omniauth_authorize_path, class: 'uk-link-reset'
              - else
                = link_to "Logout", destroy_user_session_path, method: :delete, class: 'uk-link-reset'

    .uk-container.uk-container-large
      = bootstrap_flash
      = yield
      %footer
        %p &copy; Company 2018